// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dexhaxfrgkkreqdceivm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRleGhheGZyZ2trcmVxZGNlaXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzA2MDgsImV4cCI6MjA1OTkwNjYwOH0.A5QbUqQlcJpLzV96AXnF1F1SA5zlmppM0PQGCpDdtYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);